version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.6.0
    
    working_directory: ~/todo-app

    steps:
      # Checkout repo
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      # Build and deploy
      - run: npm run build
      - run: npm run deploy